<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class C3NominalPregnancy extends Model
{
    protected $table = 'c3_nominal_pregnancies';

    protected $fillable = [
        'year',
        'quarter',
        'cidadao_pec_id',
        'cns',
        'cpf',
        'name',
        'social_name',
        'birth_date',
        'age_years',
        'phone',
        'race_color',
        'cnes',
        'facility_name',
        'district',
        'ine',
        'team_name',
        'professional_cns',
        'professional_name',
        'microarea',
        'dum',
        'dpp',
        'outcome_date',
        'puerperium_end_date',
        'gestational_age_weeks',
        'current_status',
        'month_ref',
        'mici_updated',
        'micdt_updated',
        'is_accompanied',
        'practice_a',
        'practice_b',
        'practice_c',
        'practice_d',
        'practice_e',
        'practice_f',
        'practice_g',
        'practice_h',
        'practice_i',
        'practice_j',
        'practice_k',
        'practice_a_met',
        'practice_b_met',
        'practice_c_met',
        'practice_d_met',
        'practice_e_met',
        'practice_f_met',
        'practice_g_met',
        'practice_h_met',
        'practice_i_met',
        'practice_j_met',
        'practice_k_met',
        'score_percent',
        'calculation_version',
    ];

    protected function casts(): array
    {
        return [
            'year' => 'integer',
            'quarter' => 'integer',
            'cidadao_pec_id' => 'integer',
            'birth_date' => 'date',
            'dum' => 'date',
            'dpp' => 'date',
            'outcome_date' => 'date',
            'puerperium_end_date' => 'date',
            'age_years' => 'integer',
            'gestational_age_weeks' => 'integer',
            'mici_updated' => 'boolean',
            'micdt_updated' => 'boolean',
            'is_accompanied' => 'boolean',
            'practice_a' => 'integer',
            'practice_b' => 'integer',
            'practice_c' => 'integer',
            'practice_d' => 'integer',
            'practice_e' => 'integer',
            'practice_f' => 'integer',
            'practice_g' => 'integer',
            'practice_h' => 'integer',
            'practice_i' => 'integer',
            'practice_j' => 'integer',
            'practice_k' => 'integer',
            'practice_a_met' => 'boolean',
            'practice_b_met' => 'boolean',
            'practice_c_met' => 'boolean',
            'practice_d_met' => 'boolean',
            'practice_e_met' => 'boolean',
            'practice_f_met' => 'boolean',
            'practice_g_met' => 'boolean',
            'practice_h_met' => 'boolean',
            'practice_i_met' => 'boolean',
            'practice_j_met' => 'boolean',
            'practice_k_met' => 'boolean',
            'score_percent' => 'float',
        ];
    }
}
